---
- name: Creating Credentails for ATL Tenants
  hosts: localhost
  connection: local
  vars:
     credenials_type: ATL-Credentials-Type
     credentials_name: ATL-Credentials
     custom_credential: ATL-credentials
  tasks:
     - name: Create Credential Type
       tower_credential_type:
         name: "{{ credenials_type }}"
         description: Atlanta Tenants Credentails
         kind: cloud
         inputs:
           fields:
           - id: BMASenm01_cu_key
             type: string
             label: BMASenm01_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: cbrs_cu_key
             type: string
             label: cbrs_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: cellcom_cu_key
             type: string
             label: cellcom_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: cv_cu_key
             type: string
             label: cv_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: cww_cu_key
             type: string
             label: cww_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: ekn_cu_key
             type: string
             label: ekn_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: ftc_cu_key
             type: string
             label: ftc_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: haupp_cu_key
             type: string
             label: haupp_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: ksw_cu_key
             type: string
             label: ksw_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: ntwls_cu_key
             type: string
             label: ntwls_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: tbaytel_cu_key
             type: string
             label: tbaytel_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: trial01_cu_key
             type: string
             label: trial01_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: verizon_cu_key
             type: string
             label: verizon_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: viaero_cu_key
             type: string
             label: viaero_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
         injectors:
           extra_vars:
             BMASenm01_ssh_key_file : !unsafe '{{ tower.filename.BMASenm01_key}}'
             cbrs_ssh_key_file : !unsafe '{{ tower.filename.cbrs_key}}'
             cellcom_ssh_key_file : !unsafe '{{ tower.filename.cellcom_key}}'
             cv_ssh_key_file : !unsafe '{{ tower.filename.cv_key}}'
             cww_ssh_key_file : !unsafe '{{ tower.filename.cww_key}}'
             ekn_ssh_key_file : !unsafe '{{ tower.filename.ekn_key}}'
             ftc_ssh_key_file : !unsafe '{{ tower.filename.ftc_key}}'
             haupp_ssh_key_file : !unsafe '{{ tower.filename.haupp_key}}'
             ksw_ssh_key_file : !unsafe '{{ tower.filename.ksw_key}}'
             ntwls_ssh_key_file : !unsafe '{{ tower.filename.ntwls_key}}'
             tbaytel_ssh_key_file : !unsafe '{{ tower.filename.tbaytel_key}}'
             trial01_ssh_key_file : !unsafe '{{ tower.filename.trial01_key}}'
             verizon_ssh_key_file : !unsafe '{{ tower.filename.verizon_key}}'
             viaero_ssh_key_file : !unsafe '{{ tower.filename.viaero_key}}'
           file:
             template.BMASenm01_key : !unsafe '{{ BMASenm01_cu_key }}'
             template.cbrs_key : !unsafe '{{ cbrs_cu_key }}'
             template.cellcom_key : !unsafe '{{ cellcom_cu_key }}'
             template.cv_key : !unsafe '{{ cv_cu_key}}'
             template.cww_key : !unsafe '{{ cww_cu_key }}'
             template.ekn_key : !unsafe '{{ ekn_cu_key }}'
             template.ftc_key : !unsafe '{{ ftc_cu_key }}'
             template.haupp_key : !unsafe '{{ haupp_cu_key }}'
             template.ksw_key : !unsafe '{{ ksw_cu_key }}'
             template.ntwls_key : !unsafe '{{ ntwls_cu_key }}'
             template.tbaytel_key : !unsafe '{{ tbaytel_cu_key }}'
             template.trial01_key : !unsafe '{{ trial01_cu_key }}'
             template.verizon_key : !unsafe '{{ verizon_cu_key}}'
             template.viaero_key : !unsafe '{{ viaero_cu_key }}'
         state: present
         tower_verify_ssl: false


     - name: Create a valid credential from a private_key file
       shell:
         cmd: tower-cli credential create --organization "Default" --name "{{ credentials_name }}" --credential-type  "{{ credenials_type }}"  --inputs "{'BMASenm01_cu_key':\"$( sed -z 's/\n/\\n/g' BMASenm01_cu_key.pem )\", 'cbrs_cu_key':\"$( sed -z 's/\n/\\n/g' cbrs_cu_key.pem )\", 'cellcom_cu_key':\"$( sed -z 's/\n/\\n/g' cellcom_cu_key.pem )\", 'cv_cu_key':\"$( sed -z 's/\n/\\n/g' cv_key.pem )\",'cww_cu_key':\"$( sed -z 's/\n/\\n/g' cww.pem )\", 'ekn_cu_key':\"$( sed -z 's/\n/\\n/g' ekn.pem )\", 'ftc_cu_key':\"$( sed -z 's/\n/\\n/g' ftc_cu_key.pem )\", 'haupp_cu_key':\"$( sed -z 's/\n/\\n/g' haupp_cu_key.pem )\", 'ksw_cu_key':\"$( sed -z 's/\n/\\n/g' ksw.pem )\", 'ntwls_cu_key':\"$( sed -z 's/\n/\\n/g' ntwls_cu_key.pem )\", 'tbaytel_cu_key':\"$( sed -z 's/\n/\\n/g' tbaytel_cu_key.pem )\", 'trial01_cu_key':\"$( sed -z 's/\n/\\n/g' trial01_cu_key.pem )\", 'verizon_cu_key':\"$( sed -z 's/\n/\\n/g' verizon_cu_key.pem )\", 'viaero_cu_key':\"$( sed -z 's/\n/\\n/g' viaero.pem )\"}"
       no_log: false

