---
- name: Creating Credentails for FRA Tenants
  hosts: localhost
  connection: local
  vars:
     credenials_type: FRA-Credentials-Type
     credentials_name: FRA-Credentials
     custom_credential: ATL-credentials
  tasks:
     - name: Create Credential Type
       tower_credential_type:
         name: "{{ credenials_type }}"
         description: Frankfurt Tenants Credentails
         kind: cloud
         inputs:
           fields:
           - id: BMASenm02_cu_key
             type: string
             label: BMASenm02_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: enm01xaas_cu_key
             type: string
             label: enm01xaas_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: panenm01_cu_key
             type: string
             label: panenm01_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: frstaging01_cu_key
             type: string
             label: frstaging01_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
           - id: frstagingenm02_cu_key
             type: string
             label: frstagingenm02_cu_key
             format: ssh_private_key
             secret: true
             multiline: true
         injectors:
           extra_vars:
             BMASenm02_ssh_key_file : !unsafe '{{ tower.filename.BMASenm02_key}}'
             enm01xaas_ssh_key_file : !unsafe '{{ tower.filename.enm01xaas_key}}'
             panenm01_ssh_key_file : !unsafe '{{ tower.filename.panenm01_key}}'
             frstaging01_ssh_key_file : !unsafe '{{ tower.filename.frstaging01_key}}'
             frstagingenm02_ssh_key_file : !unsafe '{{ tower.filename.frstagingenm02_key}}'
           file:
             template.BMASenm02_key : !unsafe '{{ BMASenm02_cu_key }}'
             template.enm01xaas_key : !unsafe '{{ enm01xaas_cu_key }}'
             template.panenm01_key : !unsafe '{{ panenm01_cu_key }}'
             template.frstaging01_key : !unsafe '{{ frstaging01_cu_key }}'
             template.frstagingenm02_key : !unsafe '{{ frstagingenm02_cu_key }}'
         state: present
         tower_verify_ssl: false

     - name: Create a valid credential from a private_key file
       shell:
         cmd: tower-cli credential create --organization "Default" --name "{{ credentials_name }}" --credential-type  "{{ credenials_type }}"  --inputs "{'BMASenm02_cu_key':\"$( sed -z 's/\n/\\n/g' BMASenm02_cu_key.pem )\", 'enm01xaas_cu_key':\"$( sed -z 's/\n/\\n/g' enm01xaas_cu_key.pem )\", 'panenm01_cu_key':\"$( sed -z 's/\n/\\n/g' panenm01_cu_key.pem )\", 'frstaging01_cu_key':\"$( sed -z 's/\n/\\n/g' frstaging01_cu_key.pem )\",'frstagingenm02_cu_key':\"$( sed -z 's/\n/\\n/g' frstagingenm02_cu_key_new.pem )\"}"
       no_log: false

